# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='nmb',
            new_name='count',
        ),
    ]
