# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_descriptions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
