# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-15 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180115_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
